name: Merge Repositories and replace template variables in resulting repository files

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  templated_files_variables: "__ABOUT/Description,__ORGANIZATION/taxi-gestion,__PROJECT/taxi-gestion,__REPOSITORY/client"

jobs:
  merge_template_repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout template repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          repository: codingones-github-templates/angular-client

      - name: Checkout rebase branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git checkout main
          git remote add template2 https://github.com/codingones-github-templates/aws-application-client.git
          git remote remove origin
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch template2
          git merge --allow-unrelated-histories -X theirs template2/main

      - name: Replace variables placeholders in templated (.json/.tf/.html/.md/.ts) files
        run: |
          IFS=', ' read -r -a pairs <<< "${{ env.templated_files_variables }}"
          for pair in "${pairs[@]}"; do
            IFS='/' read -r -a kv <<< "$pair"
            placeholder=${kv[0]}
            replacement=${kv[1]}
            find . -type f \( -name "*.json" -o -name "*.tf" -o -name "*.html" -o -name "*.md" -o -name "*.ts" \) -exec sed -i "s/${placeholder}/${replacement}/g" {} \;
          done

      - name: Commit and push updated files
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add . 
          git commit -m "feat: replace templated files variables"
          git push origin main --force
